[package]
name = "scaphandre"
version = "0.2.0"
authors = ["Benoit Petit <bpetit@hubblo.org>"]
edition = "2018"
license = "Apache-2.0"
description = "Electrical power consumption measurement agent."
repository = "https://github.com/hubblo-org/scaphandre"
readme = "README.md"
#homepage = "https://scaphandre.hubblo.org"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
loggerv = "0.7.2"
log = "0.4"
clap = "2.33.3"
regex = "1"
procfs = "0.8.1"
actix-web = "3"
riemann_client = "0.9.0"
hostname = "0.3.1"
protobuf = "2.20.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
warp10 = "1.0.0"
time = "0.2.25"
chrono = "0.4.19"